server:
  port: 8010
  netty:
    connection-timeout: 5000

spring:
  application:
    name: BS_SAAS_GATEWAY
#  config:
#    import: aws-secretsmanager:play/gateway/common
  http:
    codecs:
      max-in-memory-size: 10MB
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 100000 #ms
            response-timeout: 100s
            pool:
              type: fixed
              max-connections: 100
              max-idle-time: 240s
              max-life-time: 3600s
              eviction-interval: 120s
              leasing-strategy: lifo
              name: my-provider